<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2018-04-05 22:52:49.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace Tipsa\FiestasBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;

/**
 * Tipsa\FiestasBundle\Entity\FiestaPatronal
 *
 * @ORM\Entity(repositoryClass="Tipsa\FiestasBundle\Entity\FiestaPatronalRepository")
 * @ORM\Table(name="FiestaPatronal",indexes={@ORM\Index(name="fk_FiestaPatronal_Municipio1_idx", columns={"municipio_id"})})
 *
 * @ExclusionPolicy("all")
 *
 */
class FiestaPatronal
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Expose
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=250)
     * @Expose
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="text", length=500, nullable=true)
     * @Expose
     */
    protected $Descripcion;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Expose
     */
    protected $Latitud;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Expose
     */
    protected $Longitud;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Municipio_id;

    /**
     * @ORM\Column(type="date")
     * @Expose
     */
    protected $Fecha;

    /**
     * @ORM\ManyToOne(targetEntity="Municipio", inversedBy="fiestaPatronals")
     * @ORM\JoinColumn(name="municipio_id", referencedColumnName="id", nullable=false)
     * @Expose
     */
    protected $municipio;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Descripcion.
     *
     * @param string $Descripcion
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setDescripcion($Descripcion)
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    /**
     * Get the value of Descripcion.
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->Descripcion;
    }

    /**
     * Set the value of Latitud.
     *
     * @param float $Latitud
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setLatitud($Latitud)
    {
        $this->Latitud = $Latitud;

        return $this;
    }

    /**
     * Get the value of Latitud.
     *
     * @return float
     */
    public function getLatitud()
    {
        return $this->Latitud;
    }

    /**
     * Set the value of Longitud.
     *
     * @param float $Longitud
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setLongitud($Longitud)
    {
        $this->Longitud = $Longitud;

        return $this;
    }

    /**
     * Get the value of Longitud.
     *
     * @return float
     */
    public function getLongitud()
    {
        return $this->Longitud;
    }

    /**
     * Set the value of Municipio_id.
     *
     * @param integer $Municipio_id
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setMunicipioId($Municipio_id)
    {
        $this->Municipio_id = $Municipio_id;

        return $this;
    }

    /**
     * Get the value of Municipio_id.
     *
     * @return integer
     */
    public function getMunicipioId()
    {
        return $this->Municipio_id;
    }

    /**
     * Set the value of FechaInicio.
     *
     * @param \DateTime $FechaInicio
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setFecha($Fecha)
    {
        $this->Fecha = $Fecha;

        return $this;
    }

    /**
     * Get the value of FechaInicio.
     *
     * @return \DateTime
     */
    public function getFecha()
    {
        return $this->Fecha;
    }


    /**
     * Set Municipio entity (many to one).
     *
     * @param \Tipsa\FiestasBundle\Entity\Municipio $municipio
     * @return \Tipsa\FiestasBundle\Entity\FiestaPatronal
     */
    public function setMunicipio(Municipio $municipio = null)
    {
        $this->municipio = $municipio;

        return $this;
    }

    /**
     * Get Municipio entity (many to one).
     *
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function getMunicipio()
    {
        return $this->municipio;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'Descripcion', 'Latitud', 'Longitud', 'Municipio_id', 'Fecha');
    }
}
