<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2018-04-03 06:20:43.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace Tipsa\FiestasBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Tipsa\FiestasBundle\Entity\Municipio
 *
 * @ORM\Entity()
 * @ORM\Table(name="Municipio", indexes={@ORM\Index(name="fk_Municipio_Departamento_idx", columns={"departamento_id"})})
 */
class Municipio
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=250)
     */
    protected $Municipio;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Latitud;

    /**
     * @ORM\Column(type="string", length=45)
     */
    protected $Longitud;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Departamento_id;

    /**
     * @ORM\OneToMany(targetEntity="FiestaPatronal", mappedBy="municipio")
     * @ORM\JoinColumn(name="id", referencedColumnName="municipio_id", nullable=false)
     */
    protected $fiestaPatronals;

    /**
     * @ORM\ManyToOne(targetEntity="Departamento", inversedBy="municipios")
     * @ORM\JoinColumn(name="departamento_id", referencedColumnName="id", nullable=false)
     */
    protected $departamento;

    public function __construct()
    {
        $this->fiestaPatronals = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Municipio.
     *
     * @param string $Municipio
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function setMunicipio($Municipio)
    {
        $this->Municipio = $Municipio;

        return $this;
    }

    /**
     * Get the value of Municipio.
     *
     * @return string
     */
    public function getMunicipio()
    {
        return $this->Municipio;
    }

    /**
     * Set the value of Latitud.
     *
     * @param integer $Latitud
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function setLatitud($Latitud)
    {
        $this->Latitud = $Latitud;

        return $this;
    }

    /**
     * Get the value of Latitud.
     *
     * @return integer
     */
    public function getLatitud()
    {
        return $this->Latitud;
    }

    /**
     * Set the value of Longitud.
     *
     * @param string $Longitud
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function setLongitud($Longitud)
    {
        $this->Longitud = $Longitud;

        return $this;
    }

    /**
     * Get the value of Longitud.
     *
     * @return string
     */
    public function getLongitud()
    {
        return $this->Longitud;
    }

    /**
     * Set the value of Departamento_id.
     *
     * @param integer $Departamento_id
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function setDepartamentoId($Departamento_id)
    {
        $this->Departamento_id = $Departamento_id;

        return $this;
    }

    /**
     * Get the value of Departamento_id.
     *
     * @return integer
     */
    public function getDepartamentoId()
    {
        return $this->Departamento_id;
    }

    /**
     * Add FiestaPatronal entity to collection (one to many).
     *
     * @param \Tipsa\FiestasBundle\Entity\FiestaPatronal $fiestaPatronal
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function addFiestaPatronal(FiestaPatronal $fiestaPatronal)
    {
        $this->fiestaPatronals[] = $fiestaPatronal;

        return $this;
    }

    /**
     * Remove FiestaPatronal entity from collection (one to many).
     *
     * @param \Tipsa\FiestasBundle\Entity\FiestaPatronal $fiestaPatronal
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function removeFiestaPatronal(FiestaPatronal $fiestaPatronal)
    {
        $this->fiestaPatronals->removeElement($fiestaPatronal);

        return $this;
    }

    /**
     * Get FiestaPatronal entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getFiestaPatronals()
    {
        return $this->fiestaPatronals;
    }

    /**
     * Set Departamento entity (many to one).
     *
     * @param \Tipsa\FiestasBundle\Entity\Departamento $departamento
     * @return \Tipsa\FiestasBundle\Entity\Municipio
     */
    public function setDepartamento(Departamento $departamento = null)
    {
        $this->departamento = $departamento;

        return $this;
    }

    /**
     * Get Departamento entity (many to one).
     *
     * @return \Tipsa\FiestasBundle\Entity\Departamento
     */
    public function getDepartamento()
    {
        return $this->departamento;
    }

    public function __sleep()
    {
        return array('id', 'Municipio', 'Latitud', 'Longitud', 'Departamento_id');
    }
}
